#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The conversion service provides a set of basic conversion definition types that allows the specification of a conversion between two representations. These conversions are used by the other MC services (such as Action, Alert, and Parameter) to define conversions from raw field representations to some engineering representation.
Conversions are associated with other entities such as parameters or action/alert arguments through the configuration of the relevant service (action/alert/parameter).
The conversion service does not provide any operations directly, but allows consumers to add, remove, and modify conversion definitions via the COM archive."""

from enum import IntEnum
from mo import mal
from mo import com
from mo.mc import *

number = 7
# Composite
## DiscreteConversionDetails
## LineConversionDetails
## PolyConversionDetails
## RangeConversionDetails


