#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The action service allows consumers to submit an action for execution and to subsequently monitor the execution progress of these actions."""

from enum import IntEnum
from malpy.mo import mal
from malpy.mo import mc

number = 1

# CapabilitySet 1
class RequestExecutionProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 1
    OPERATION = 7


class RequestExecutionConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 1
    OPERATION = 7



# CapabilitySet 4
class MonitorActionExecProviderHandler(mal.PubSubProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 1
    OPERATION = 8


class MonitorActionExecConsumerHandler(mal.PubSubConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 1
    OPERATION = 8


