#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The aggregation service allows the user to acquire several parameter values in a single request."""

from enum import IntEnum
from malpy.mo import mal
from malpy.mo import mc

number = 6

# CapabilitySet 1
class MonitorValueProviderHandler(mal.PubSubProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 1


class MonitorValueConsumerHandler(mal.PubSubConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 1



# CapabilitySet 2
class GetValueProviderHandler(mal.RequestProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 2


class GetValueConsumerHandler(mal.RequestConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 2



# CapabilitySet 3
class GetReportingConfigurationProviderHandler(mal.RequestProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 9


class GetReportingConfigurationConsumerHandler(mal.RequestConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 9


class EnableReportingProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 10


class EnableReportingConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 10


class DisableReportingProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 11


class DisableReportingConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 11


class SetReportingPeriodProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 12


class SetReportingPeriodConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 12



# CapabilitySet 5
class AddAggregationProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 6


class AddAggregationConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 6


class RemoveAggregationProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 8


class RemoveAggregationConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 6
    OPERATION = 8


