#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The packet service allows a consumer to subscribe to a subset of the space packets, with filtering capabilities based on packets metadata."""

from enum import IntEnum
from malpy.mo import mal
from malpy.mo import mc

number = 9

# CapabilitySet 1
class DeliverPacketProviderHandler(mal.PubSubProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 9
    OPERATION = 1


class DeliverPacketConsumerHandler(mal.PubSubConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 9
    OPERATION = 1


