#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The parameter service allows the user to subscribe to parameter value report and optionally be able to set new values."""

from enum import IntEnum
from malpy.mo import mal
from malpy.mo import mc

number = 2

# CapabilitySet 1
class MonitorValueProviderHandler(mal.PubSubProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 1


class MonitorValueConsumerHandler(mal.PubSubConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 1



# CapabilitySet 2
class GetValueProviderHandler(mal.RequestProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 2


class GetValueConsumerHandler(mal.RequestConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 2



# CapabilitySet 3
class SetValueProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 3


class SetValueConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 3



# CapabilitySet 4
class GetReportingConfigurationProviderHandler(mal.RequestProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 9


class GetReportingConfigurationConsumerHandler(mal.RequestConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 9


class EnableReportingProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 10


class EnableReportingConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 10


class DisableReportingProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 11


class DisableReportingConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 11


class SetReportingPeriodProviderHandler(mal.SubmitProviderHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 12


class SetReportingPeriodConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 4
    VERSION = 2
    SERVICE = 2
    OPERATION = 12


