#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The Order Management Service, introduced in §2.5, is used to submit and manage standing orders.  Standing orders specify a product filter to subscribe to a subset of automatically generated products and define the method and destination for product delivery."""

from enum import IntEnum
from malpy.mo import mal
from malpy.mo import mpd

number = 2

# CapabilitySet 1
class ListStandingOrdersProviderHandler(mal.RequestProviderHandler):
    AREA = 9
    VERSION = 1
    SERVICE = 2
    OPERATION = 1


class ListStandingOrdersConsumerHandler(mal.RequestConsumerHandler):
    AREA = 9
    VERSION = 1
    SERVICE = 2
    OPERATION = 1


class SubmitStandingOrderProviderHandler(mal.RequestProviderHandler):
    AREA = 9
    VERSION = 1
    SERVICE = 2
    OPERATION = 2


class SubmitStandingOrderConsumerHandler(mal.RequestConsumerHandler):
    AREA = 9
    VERSION = 1
    SERVICE = 2
    OPERATION = 2


class CancelStandingOrderProviderHandler(mal.SubmitProviderHandler):
    AREA = 9
    VERSION = 1
    SERVICE = 2
    OPERATION = 3


class CancelStandingOrderConsumerHandler(mal.SubmitConsumerHandler):
    AREA = 9
    VERSION = 1
    SERVICE = 2
    OPERATION = 3


