# SPDX-FileCopyrightText: 2025 CNES
#
# SPDX-License-Identifier: MIT

#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The Product Retrieval Service, introduced in §2.5, enables browsing and retrieval of existing products."""

from enum import IntEnum
from malpy.mo import mal
from malpy.mo import mpd

number = 1

# CapabilitySet 1
class ListProductsProviderHandler(mal.RequestProviderHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 1
    OPERATION = 1


class ListProductsConsumerHandler(mal.RequestConsumerHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 1
    OPERATION = 1


class GetProductsProviderHandler(mal.ProgressProviderHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 1
    OPERATION = 2


class GetProductsConsumerHandler(mal.ProgressConsumerHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 1
    OPERATION = 2


class GetProductFilesProviderHandler(mal.ProgressProviderHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 1
    OPERATION = 3


class GetProductFilesConsumerHandler(mal.ProgressConsumerHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 1
    OPERATION = 3


