#####################################################
# Generated by generators/generator.py              #
# This file is generated. Do NOT edit it by hand.   #
#####################################################

"""The Product Delivery Service, introduced in §2.5, is used in conjunction with existing standing orders (for the delivery of selected products).  File delivery of products, if requested in the standing order, will be delivered without the need to use these service operations. The service provides two capabilities to the the consumer: to receive notifications each time their ordered products have been delivered as files to receive the ordered products via message transfer rather than file delivery"""

from enum import IntEnum
from malpy.mo import mal
from malpy.mo import mpd

number = 3

# CapabilitySet 1
class NotifyProductDeliveryProviderHandler(mal.PubSubProviderHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 3
    OPERATION = 1


class NotifyProductDeliveryConsumerHandler(mal.PubSubConsumerHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 3
    OPERATION = 1


class DeliverProductsProviderHandler(mal.PubSubProviderHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 3
    OPERATION = 2


class DeliverProductsConsumerHandler(mal.PubSubConsumerHandler):
    AREA = 9
    AREA_VERSION = 1
    SERVICE = 3
    OPERATION = 2


